# 项目相关配置
demo:
  #缓存类型  0:本地缓存,  1:redis
  cacheType: 1
  #模块开关 0 代表禁用，1 代表开启
  moduleSwitch:
    #iot模块
    jmiot: 1
# 环境配置
server:
  # 服务器的HTTP端口，默认为19000
  port: 19001
  servlet:
    # 应用的访问路径
    context-path: /iotApi
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.zw: info
    org.springframework: warn

# Spring配置
spring:
  # redis 配置
  redis:
    # 地址
    host: 10.168.136.128
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: jcca@123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

